- name: "Set SSH Enviorment to alternate port"
  shell: "ufw allow ssh && \
            ufw allow 2002/tcp"

- name: Creates SSH hidden directory
  file:
      path: "/home/{{deploy_user}}/.ssh"
      state: directory

- name: Copy a "sshd_config" file from repo to the remote machine
  copy:
    src: "/home/{{deploy_user}}/repos/{{repo_name}}/defaults/sshd_config"
    dest: "/etc/ssh/sshd_config"

- name: "Restart SSH Service"
  shell: "systemctl restart sshd"

- name: "Create Endless SSH Docker Container"
  ignore_errors: true
  shell: "docker rm -f endlessh && docker run -d \
      --name=endlessh \
      -e PUID=1000 \
      -e PGID=1000 \
      -e TZ=America/Toronto \
      -e MSDELAY=10000 `#optional` \
      -e MAXLINES=32 `#optional` \
      -e MAXCLIENTS=4096 `#optional` \
      -e LOGFILE=true `#optional` \
      -e BINDFAMILY= `#optional` \
      -p 22:2222 \
      -v {{homedir}}/container-program-files/endlessh:/config `#optional` \
      --restart unless-stopped \
      lscr.io/linuxserver/endlessh"

- name: "Remove and dissable GUI in Ubuntu"
  shell: "apt-get purge ubuntu-desktop -y && \
            systemctl set-default multi-user"
  ignore_errors: true
  no_log: true